spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${qlink-api.db.address}/postgres
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop